// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();
    console.log('[auth-middleware] request available:', !!request);
    console.log('[auth-middleware] request headers available:', !!request?.headers);

    if (!request?.headers) {
      console.error('[auth-middleware] No request headers available');
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');
    console.log('[auth-middleware] authorization header present:', !!authHeader);

    if (!authHeader) {
      // Log all headers for debugging
      const allHeaders: Record<string, string> = {};
      request.headers.forEach((val, key) => { allHeaders[key] = val; });
      console.error('[auth-middleware] No authorization header. Headers received:', JSON.stringify(allHeaders));
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    console.log('[auth-middleware] token extracted, length:', token.length);

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getUser(token);
    console.log('[auth-middleware] getUser result - user:', !!data?.user, 'error:', error?.message);
    if (error || !data?.user) {
      console.error('[auth-middleware] getUser failed:', error);
      throw new Error('Unauthorized: Invalid token');
    }

    if (!data.user.id) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId: data.user.id,
        claims: { ...data.user.user_metadata, sub: data.user.id, email: data.user.email },
      },
    });
  },
);
